---
- name: Exercise 3b 
  hosts: nxos 
  gather_facts: False 
  tasks:
    - name: Get output from show commands 
      nxos_command: 
        commands: 
          - show version 
          - show lldp neighbors 
      register: sh_cmds
    - name: Show output 
      debug:
        msg: "{{ sh_cmds }}" 

