---
- name: Configure devices using Jinja2 template 
  hosts: cisco:nxos:arista:juniper
  gather_facts: True
  tasks:
    - name: Working on IOS and IOS-XE devices...
      ios_config:
        src: ios/global.j2
        save_when: changed
        diff_against: running
      when: ansible_facts.net_system == "ios"
      tags: cisco
  
    - name: Working on NX-OS devices
      nxos_config:
        src: nxos/global.j2
        save_when: changed
        diff_against: running
      when: ansible_facts.net_system == "nxos"
      tags: nxos
   
    - name: Working on Juniper devices
      junos_config:
        src: "junos/global.j2"
        update: merge
      when: ansible_facts.net_system == "junos"
      tags: junos

    - name: Working on Arista devices
      eos_config:
        src: eos/global.j2
        save_when: changed
        diff_against: running
      when: ansible_facts.net_system == "eos"
      tags: eos
      
    - name: debug facts
      debug:
        var: ansible_facts
      tags: debug 
