---
- name: Exercise 3
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Configure interface e1/4
      nxos_l3_interfaces:
        config:
        - name: Ethernet1/4
          ipv4:
          - address: "{{ ip_addr }}/{{ net_mask }}"
        state: merged
