---
- name: Exercise 5
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Configure switchport on {{ intf_name }}
      nxos_interfaces:
        config:
        - name: "{{ intf_name }}"
          mode: "{{ intf_mode }}"
          description: "{{ description }}"
        state: merged

    - name: Configure {{ intf_name }} as {{ switchport_mode }}
      nxos_l2_interface:
        name: "{{ intf_name }}"
        mode: "{{ switchport_mode }}"

    - name: Configure {{ intf_name }} for native VLAN {{ native_vlan }} 
      nxos_l2_interfaces:
        config:
        - name: "{{ intf_name }}"
          trunk:
            native_vlan: "{{ native_vlan }}"
        state: merged

    - name: Run `show interface {{ intf_name }} trunk | json`
      nxos_command:
        commands: "show interface {{ intf_name }} trunk | json "
      register: trunk
      tags: check

    - name: Store the output for {{ intf_name }} 
      set_fact:
        check_dict:  '{{ trunk["stdout"][0].TABLE_interface.ROW_interface }}'
      tags: check

    - name: Run assert test to check trunk status for {{ intf_name }}
      assert:
        that:
          - check_dict.interface == "{{ intf_name }}"
          - check_dict.native == "{{ native_vlan }}"
          - check_dict.status == 'trunking'
      tags: check
