---
- name: View running configuration
  hosts: nxos
  gather_facts: False
  tasks:
    - name: Show interfaces
      nxos_command:
        commands: show run int {{ intf_name }}
      register: intf
      
    - debug:
        var: intf["stdout_lines"][0]
