---
- name: Exercise 1
  hosts: cisco
  gather_facts: False
  tasks:
    - name: Create a banner for Cisco devices
      ios_banner:
        banner: login
        text: | 
          ======================================== 
                     /\
                    /  \
                   /    \
                  /      \
                 /        \
                /__________\
               /\__________/\
              /  \        /  \
             /    \      /    \
            /      \    /      \
           /        \  /        \
          /__________\/__________\
          \__________/\__________/
             Managed by Ansible 
          ======================================== 
        state: present  
      tags: banner_add
      notify: write mem
  
  handlers:
    - name: write mem
      ios_command: 
        commands: write mem
      changed_when: True
