---
- name: Exercise 3
  hosts: cisco1:cisco2
  gather_facts: False
  tasks:
    - name: Gather output from `show lldp neighbors`
      ios_command:
        commands: show lldp neighbors 
      register: neighbors 

    - name: Register snipped version from neighbor output
      set_fact:
        neighbor_snip: "{{ neighbors.stdout_lines[0] }}"

    - name: Parse for a specific line
      set_fact:
        lldp_entry: "{{ item }}" 
      loop: "{{ neighbor_snip }}"
      when: "'twb-sf-hpsw1' in item"

    - name: convert line to a list 
      set_fact:
        lldp_list: "{{ lldp_entry.split() }}"
  
    - name: register variables
      set_fact:
        remote_device: "{{ lldp_list[0] }}"
        local_intf: "{{ lldp_list[1] }}"
        remote_intf: "{{ lldp_list[-1] }}"

    - name: Display parsed neighbor output
      debug: 
        msg: 
          - "Remote device: {{ remote_device }}"
          - "Local intf: {{ local_intf }}"
          - "Remote intf: {{ remote_intf }}" 
