---
- name: Exercise 4a
  hosts: cisco6
  gather_facts: False 
  tasks: 
    - name: Clear Logging Buffer 
      ios_command:
        commands: 
          - command: clear logging
            prompt: confirm
            answer: y
      register: output
    - name: Display output 
      debug:
        var: output
