---
- name: Configure IOS ACL's with a deny statement
  hosts: cisco5:cisco6
  gather_facts: False
  tasks:
    - name: Use ios_config to create {{ acl_name }} 
      ios_config:
        before: "no ip access-list extended {{ acl_name }}"
        parents: "ip access-list extended {{ acl_name }}"
        lines:
          - deny   ip host 10.1.1.9 any
          - permit ip host 10.1.1.1 any
          - permit ip host 10.1.1.2 any
          - permit ip host 10.1.1.3 any
          - permit ip host 10.1.1.4 any
          - permit ip host 10.1.1.5 any
          - permit ip host 10.1.1.6 any
          - permit ip host 10.1.1.7 any
          - permit ip host 10.1.1.8 any
          - permit ip host 10.1.1.10 any
        match: exact
        replace: block
    
    - name: Verify {{ acl_name }} ACL configurations
      ios_command:
        commands: "show access-list {{ acl_name }}"
      register: acl_config

    - name: View output from {{ acl_name }}
      debug:
        var: acl_config.stdout_lines[0]

