---
- name: Exercise 5c
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Run `show interface terse`
      junos_command:
        commands: show interfaces terse
      register: interfaces
    - name: Get single interface  
      set_fact:
        port: "{{ interfaces['stdout_lines'][0][21] }}"
    - name: Display IP only 
      debug:
        msg: "Primary IP: {{ port.split()[-1] }}" 
