---
- name: Exercise 6a
  hosts: arista
  gather_facts: False
  tasks:
    - name: Run `show ip arp` 
      eos_command:
        commands:
          - show ip arp 
      register: show_ip_arp
    - name: Display output
      debug: 
        var: show_ip_arp
