---
- name: Exercise 1a 
  hosts: arista:cisco:juniper
  gather_facts: True 
  tasks:
    - name: Retrieve `show ip arp` (eos)
      eos_command: 
        commands: show ip arp 
      register: show_ip_arp_eos
      when: ansible_network_os == "eos"

    - name: Retrieve `show ip arp` (ios)
      ios_command: 
        commands: show ip arp 
      register: show_ip_arp_ios
      when: ansible_network_os == "eos"

    - name: Retrieve `show arp` (junos)
      junos_command: 
        commands: show arp
      register: show_arp_junos
      when: ansible_network_os == "junos"
   
    - name: Display ARP output
      debug:
        var: show_ip_arp_eos
      when: ansible_network_os == "eos"
    
