---
- name: Exercise 2
  hosts: nxos
  gather_facts: False 
  tasks:
    - name: Get the output from `show vlan id`
      nxos_command:
        commands: "show vlan id {{ item }}"
      loop:
        - 1
        - 2
        - 3
        - 4
      register: vlans

    - name: Get output of from vlan id 4
      debug:
        var: vlans.results.3.stdout_lines
      
      
