---
- name: Exercise 3c
  hosts: nxos 
  gather_facts: False 
  tasks:
    - name: Get output from show commands 
      nxos_command: 
        commands: 
          - show version 
          - show lldp neighbors 
      register: sh_cmds
    - name: Show lldp neighbors 
      debug:
        var: sh_cmds["stdout_lines"][1]

