---
- name: Import external tasks to configure IOS/IOS-XE devices
  hosts: cisco
  gather_facts: True
  tasks:
    - name: Configure IOS devices
      import_tasks: ios_cfg.yml
      when: ansible_facts.net_iostype == "IOS"

    - name: Configure IOS-XE devices
      import_tasks: iosxe_cfg.yml
      when: ansible_facts.net_iostype == "IOS-XE"
