---
- name: Import external tasks to configure IOS/IOS-XE devices
  hosts: cisco
  gather_facts: True
#  vars: 
#    - ntp_server1: 130.126.24.24
#    - ntp_server2: 152.2.21.1
#    - domain_name: bogus.com
#    - dns_server1: 8.8.8.8
#    - dns_server2: 8.8.4.4
  tasks:
    - name: Configure IOS devices
      import_tasks: ios_cfg.yml
      when: ansible_facts.net_iostype == "IOS"

    - name: Configure IOS-XE devices
      import_tasks: iosxe_cfg.yml
      when: ansible_facts.net_iostype == "IOS-XE"
