---
- name: Exercise 6b
  hosts: arista
  gather_facts: False
  tasks:
    - name: Run `show ip arp` 
      eos_command:
        commands:
          - show ip arp 
      register: show_ip_arp

    - name: Run `show ip arp | json` 
      eos_command:
        commands:
          - show ip arp | json 
      register: show_ip_arp_json
    - name: Display output from `show ip arp` 
      debug: 
        var: show_ip_arp 
    - name: Display json output from `show ip arp`
      debug: 
        var: show_ip_arp_json 
  
            
            
