---
- name: Exercise 1e
  hosts: arista5
  gather_facts: True
  vars_files: my_vars.yml
  tasks:
    - name: Print all facts 
      debug:
        var: ansible_facts 
    - name: Print 1 fact 
      debug: 
        var: net_all_ipv4_addresses 
    - name: Print network inventory facts 
      debug: 
        var: ansible_network_os
    - name: Print host inventory facts 
      debug:
        var: ansible_host
    - name: Print desired state
      debug: 
        var: desired_eos_version
    - name: set fact 
      set_fact:
        device_hostname: "{{ inventory_hostname }}.lab.io"
    - name: print set fact 
      debug: 
        var: device_hostname
