---
- name: View current vlans
  hosts: arista
  gather_facts: False
  tasks:
    - name: perform `sh vlan brief`
      eos_command:
        commands: show vlan brief
      register: vlan_brief
      tags: eoss
      when: "ansible_network_os == 'eos'"

    - name: view brief output of vlans 
      debug:
        var: vlan_brief["stdout_lines"]
      tags: eoss
    
    - name: perform `show vlan | json`
      eos_command:
        commands: "show vlan | json"
      register: vlan_json
      tags: eos
      when: "ansible_network_os == 'eos'"
      
    - name: view json output of vlans
      debug:
        var: '{{ vlan_json.stdout[0].vlans[vlan_num] }}'
      tags: eos
        #intf_dict: var: vlan_json.stdout_lines[0].vlans["211"].interfaces
