---
- name: Exercise 1a
  hosts: arista5
  gather_facts: True
  tasks:
    - name: Print all facts 
      debug:
        var: ansible_facts 
    - name: Print 1 fact 
      debug: 
        var: net_all_ipv4_addresses 
